name: Build Unsigned APK & IPA and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release_unsigned:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JavaScript dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Set up JDK (for Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build Unsigned Android APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon
          cd ..
          APK_RELEASE_PATH=$(find android/app/build/outputs/apk/release -name 'app-release.apk' | head -n 1)
          if [ -z "$APK_RELEASE_PATH" ]; then
            exit 1
          fi
          mv "$APK_RELEASE_PATH" ZINE.apk

      # - name: Setup Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '16.0'

      # - name: Build and Archive iOS (Unsigned)
      #   run: |
      #     echo "Building workspace: ios/zine.xcworkspace, scheme: zine"
      #     xcodebuild \
      #       -workspace ios/zine.xcworkspace \
      #       -scheme zine \
      #       -configuration Release \
      #       archive \
      #       -archivePath build/zine.xcarchive \
      #       CODE_SIGN_IDENTITY="" \
      #       CODE_SIGNING_REQUIRED=NO \
      #       CODE_SIGNING_ALLOWED=NO

      # - name: Package Unsigned IPA from Archive
      #   run: |
      #     ARCHIVE_PATH="build/zine.xcarchive"
      #     APP_NAME="zine.app"
      #     APP_PATH_IN_ARCHIVE="$ARCHIVE_PATH/Products/Applications/$APP_NAME"
      #     IPA_NAME="ZINE.ipa"

      #     if [ ! -d "$APP_PATH_IN_ARCHIVE" ]; then
      #       ls -lR "$ARCHIVE_PATH/Products/Applications/"
      #       exit 1
      #     fi

      #     mkdir Payload
      #     cp -R "$APP_PATH_IN_ARCHIVE" Payload/
      #     zip -r "$IPA_NAME" Payload/
      #     rm -rf Payload

      - name: Create GitHub Release and Upload Unsigned Builds
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ZINE.apk
            ZINE.ipa
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
